project_id = "qpmxcrzqnywnutvriztq"

[functions.admin-create-user]
verify_jwt = true

[functions.send-booking-email]
verify_jwt = true

[functions.send-booking-reminders]
verify_jwt = false

[functions.google-calendar-test-connection]
verify_jwt = true

[functions.google-calendar-sync]
verify_jwt = false

[functions.check-sync-health]
verify_jwt = false
